@startuml
'https://plantuml.com/sequence-diagram

autonumber

!include Style.puml
participant CommandList << class >>
 -> CommandList: executeShoot("1")
activate CommandList

participant "curPlayer:Player" as Player
CommandList -> Player: shootDirectionAdjust(1)
activate Player
return adjustedDirection

participant Ai << class >>
CommandList -> Ai: getAiDirection()
activate Ai
return aiDir

CommandList -> Player: aiDirectionAdjust(aiDir)
activate Player
return adjustedAiDirection

CommandList -> Player: rangeAdjust()
activate Player
return adjustedRange

CommandList -> CommandList: goalCheck(adjustedAiDirection, adjustedDirection, adjustedRange)
activate CommandList
return isScoreGoal

participant MatchStat << class >>
CommandList -> MatchStat: updateStat(isScoreGoal)
activate MatchStat
MatchStat -> MatchStat: decideMatchEnd()
activate MatchStat
return

return


CommandList -> Player: printGoalAfterShoot(isScoreGoal, adjustedDirection)
activate Player

return

return
deactivate CommandList
@enduml
